feat: persist variant genomes with a deterministic ID (#255)
* feat: persist variant genomes with a deterministic ID

- variant genomes deterministic id calculated by hashing variants and
  genome config
- persist hash components using data manager (1 file / variant genome)
- make VariantGenome equality more strict. previously two variant sets
on different chromosomes with the same start could compare unequal
because the ordering was only by `start` attribute.

also: fix broken compilation due to unpinned libcxx

https://releases.llvm.org/23.1.0/projects/libcxx/docs/ReleaseNotes.html
libcxx 23 release notes say:
> libc++ has dropped a lot of transitive includes

this presents itself as many errors like
src/genome_track_io.cpp:639:2: error: no member named 'throw_with_nested' in namespace 'std'
  639 |         GK_RETHROW("for '{}'", interval);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

The last successful build was with libcxx 22.1.8, failed one is with
23.1.2.